# Site settings
title: Tay M
description: Your site description
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://hbtasdem.github.io/taymarble/" # The base hostname & protocol for your site

# Build settings
theme: midnight # The Jekyll theme you want to use
plugins:
  - jekyll-feed

# Exclude files/folders from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  highlighter_opts:
    css_class: highlight

# Pagination settings
paginate: 5 # Number of posts per page

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html
